# Generated by Django 5.2.16 on 2026-07-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Function to raise exception on UPDATE or DELETE
            CREATE OR REPLACE FUNCTION prevent_update_delete_audit()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Audit logs are read-only and append-only. UPDATE and DELETE are prohibited on % table.', TG_TABLE_NAME;
            END;
            $$ LANGUAGE plpgsql;

            -- Trigger for tickets_historialticket
            DROP TRIGGER IF EXISTS no_update_delete_historial_ticket ON tickets_historialticket;
            CREATE TRIGGER no_update_delete_historial_ticket
            BEFORE UPDATE OR DELETE ON tickets_historialticket
            FOR EACH ROW EXECUTE FUNCTION prevent_update_delete_audit();

            -- Trigger for usuarios_historialrol
            DROP TRIGGER IF EXISTS no_update_delete_historial_rol ON usuarios_historialrol;
            CREATE TRIGGER no_update_delete_historial_rol
            BEFORE UPDATE OR DELETE ON usuarios_historialrol
            FOR EACH ROW EXECUTE FUNCTION prevent_update_delete_audit();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS no_update_delete_historial_ticket ON tickets_historialticket;
            DROP TRIGGER IF EXISTS no_update_delete_historial_rol ON usuarios_historialrol;
            DROP FUNCTION IF EXISTS prevent_update_delete_audit();
            """
        )
    ]
