# Generated by Django 5.2.16 on 2026-07-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=15, unique=True)),
                ('horas_objetivo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Prioridad SLA',
                'verbose_name_plural': 'Prioridades SLA',
            },
        ),
    ]
