# Generated by Django 5.2.16 on 2026-07-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_prioridadsla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agente_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialticket',
            name='tipo',
            field=models.CharField(choices=[('estado', 'Estado'), ('prioridad', 'Prioridad'), ('sector', 'Sector'), ('asignacion', 'Asignación')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('estado', 'Estado'), ('prioridad', 'Prioridad'), ('sector', 'Sector'), ('comentario', 'Comentario'), ('asignacion', 'Asignación')], max_length=15),
        ),
    ]
