# Generated by Django 5.2.16 on 2026-07-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_emails',
            field=models.BooleanField(default=True),
        ),
    ]
