# Generated by Django 5.2.16 on 2026-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_recibir_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15),
        ),
    ]
